name: Dev - Build and deploy

on:
  push:
    branches:
      - dev

env:
  ARTIFACT_NAME: 'dev-michaelouellette' # set this to the name you want for the artifact
  NODE_VERSION: '22.x'                # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Node.js version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Cache Node Modules
      id: npm-cache
      uses: actions/cache@v5
      with:
        path: "**/node_modules"
        key: mononode-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - name: NPM Install
      if: steps.npm-cache.outputs.cache-hit != 'true'
      run: npm ci --legacy-peer-deps
    - name: Build App
      run: |
        npm run build:ssr
    - name: Archive Develop Artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.ARTIFACT_NAME }}-${{ github.sha }}
        path: dist/app/browser
        include-hidden-files: true

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        id: download
        uses: actions/download-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}-${{ github.sha }}
      - name: Display structure of downloaded files
        run: |
            # Output artifact contents.
            ls -Ra
