# @format

name: Style Lint Check

on:
  push:
    branches:
      - dev
    paths:
      - '*/**.scss'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node Modules
        id: npm-cache
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: mononode-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: NPM Install
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Style Lint
        run: |
          cd src/app
          npm run stylelint
